test:readCardDemo.cpp
	g++ -o yzwlReadCardDemo readCardDemo.cpp -std=c++11 -ggdb -ffunction-sections -O0 -Wl,-gc-sections,--no-as-needed -ldl -L./ -lreadCardInfo

clean:
	rm -rf a.bmp
	rm -rf yzwlReadCardDemo
